name: Deploy Chica-admin

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Create .env file for build
        run: echo "${{ secrets.PROD_ENV }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Prisma DB pull & generate
        run: |
          npx prisma db pull --schema=./prisma/schema.prisma
          npx prisma generate --schema=./prisma/schema.prisma

      - name: Build project (standalone)
        run: npm run build

      - name: Compress standalone output
        run: |
          tar -czf standalone.tar.gz \
          -C .next/standalone . \
          -C . public package.json next.config.js .env

      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "standalone.tar.gz"
          target: "~/deploy"

      - name: Deploy on EC2 and restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/chica-admin
            tar -xzf ~/deploy/standalone.tar.gz -C ~/chica-admin --strip-components=0
            cd ~/chica-admin
            pm2 delete chica-admin || true
            pm2 start .next/standalone/server.js --name chica-admin
            pm2 save
